# Site settings
title: Edward-Lombe
email: your-email@domain.com
description: The portfolio and blog of Edward Lombe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Edward-Lombe.github.io.com" # the base hostname & protocol for your site
twitter_username: edlombe
github_username:  Edward-Lombe

# Build settings
markdown: kramdown
